#!/bin/bash 

flutter build web --profile --web-renderer canvaskit --target=lib/main_prod.dart --output=/var/www/water.biissa.com --no-tree-shake-icons
# flutter build web --target=lib/main_dev.dart --output=../biissa-water-web --base-href=/app/ --profile --dart-define=Dart2jsOptimization=O0 #for debug mode